/**
 * Study-buddy registry.
 *
 * Artwork is generated by `scripts/extract-buddies.py` (local-only, like the
 * sticker pipeline) from `promo/new-study-buddies.png` (full-body) and
 * `promo/new-profile-and-study-buddies.png` + `promo/tango-face-only-for-study-buddy.png`
 * (faces). Adding a buddy means a new entry here, translated phrase sets under
 * `Shop.buddies.<key>` in both messages/en.json and ja.json, and a re-run of
 * that script.
 */

export const BUDDY_FACE_COUNT = 8;

export const DEFAULT_BUDDY_KEY = 'buddy_tango';

interface BuddyArt {
  /** Filename stem under public/buddies/ — not always the item key */
  id: string;
  accent: string;
  bg: string;
}

export const BUDDY_ART: Record<string, BuddyArt> = {
  buddy_tango: { id: 'tango', accent: '#A78BFA', bg: '#FDE4E3' },
  buddy_bunny: { id: 'bunny', accent: '#FDA4AF', bg: '#FDECF1' },
  buddy_penguin: { id: 'penguin', accent: '#7DD3FC', bg: '#EAF4FD' },
  buddy_panda: { id: 'panda', accent: '#86EFAC', bg: '#EBF8EE' },
  buddy_fox: { id: 'fox', accent: '#34D399', bg: '#FEF6E2' },
  buddy_pink_cat: { id: 'calico', accent: '#FDBA74', bg: '#F5E5F6' },
  buddy_otter: { id: 'otter', accent: '#A78BFA', bg: '#E9E5FA' },
  buddy_lucky_cat: { id: 'luckycat', accent: '#F472B6', bg: '#FDE9F0' },
  buddy_kappa: { id: 'kappa', accent: '#4ADE80', bg: '#FDF4DB' },
  buddy_tanuki: { id: 'tanuki', accent: '#FBBF24', bg: '#E5ECF9' },
};

export function resolveBuddyKey(key: string | null | undefined): string {
  return key && BUDDY_ART[key] ? key : DEFAULT_BUDDY_KEY;
}

export function buddyFaceSrc(key: string, variant: number): string {
  const art = BUDDY_ART[key] ?? BUDDY_ART[DEFAULT_BUDDY_KEY];
  const v = Math.min(Math.max(1, Math.round(variant)), BUDDY_FACE_COUNT);
  return `/buddies/faces/${art.id}-${v}.webp`;
}

export function buddyShopSrc(key: string): string {
  const art = BUDDY_ART[key] ?? BUDDY_ART[DEFAULT_BUDDY_KEY];
  return `/buddies/shop/${art.id}.webp`;
}

export function randomFaceVariant(): number {
  return 1 + Math.floor(Math.random() * BUDDY_FACE_COUNT);
}

export const FALLBACK_REACTIONS: Record<'correct' | 'wrong' | 'idle', string[]> = {
  correct: ['Yay! You got it!', 'Amazing!', 'Sugoi!', 'That was great!'],
  wrong: ['Almost! Try again!', "Don't give up!", 'One more try!'],
  idle: ["Let's study together!", '~cheers you on~', 'You can do it!'],
};
