/**
 * Study-buddy registry.
 *
 * Artwork is generated by `scripts/extract-buddies.py` (local-only, like the
 * sticker pipeline) from `promo/new-study-buddies.png` (full-body) and
 * `promo/new-profile-and-study-buddies.png` + `promo/tango-face-only-for-study-buddy.png`
 * (faces). Momiji's shop pose comes from `promo/tanuki-study-buddy-many.png`,
 * her faces from `promo/momiji-faces.png`, and the coming-soon teaser cutouts
 * from `promo/momo-maru.png`, and the memory scenes from `promo/<id>-l<2..5>.png`.
 * Adding a buddy means a new entry here, translated phrase sets under
 * `Shop.buddies.<key>` in both messages/en.json and ja.json, and a re-run of
 * that script.
 */

export const BUDDY_FACE_COUNT = 8;

export const DEFAULT_BUDDY_KEY = 'buddy_tango';

interface BuddyArt {
  /** Filename stem under public/buddies/ — not always the item key */
  id: string;
  accent: string;
  bg: string;
}

export const BUDDY_ART: Record<string, BuddyArt> = {
  buddy_tango: { id: 'tango', accent: '#A78BFA', bg: '#FDE4E3' },
  buddy_bunny: { id: 'bunny', accent: '#FDA4AF', bg: '#FDECF1' },
  buddy_penguin: { id: 'penguin', accent: '#7DD3FC', bg: '#EAF4FD' },
  buddy_panda: { id: 'panda', accent: '#86EFAC', bg: '#EBF8EE' },
  buddy_fox: { id: 'fox', accent: '#34D399', bg: '#FEF6E2' },
  buddy_pink_cat: { id: 'calico', accent: '#FDBA74', bg: '#F5E5F6' },
  buddy_otter: { id: 'otter', accent: '#A78BFA', bg: '#E9E5FA' },
  buddy_lucky_cat: { id: 'luckycat', accent: '#F472B6', bg: '#FDE9F0' },
  buddy_kappa: { id: 'kappa', accent: '#4ADE80', bg: '#FDF4DB' },
  buddy_tanuki: { id: 'tanuki', accent: '#FBBF24', bg: '#E5ECF9' },
  buddy_red_panda: { id: 'redpanda', accent: '#FB923C', bg: '#FDF3E2' },
};

export function resolveBuddyKey(key: string | null | undefined): string {
  return key && BUDDY_ART[key] ? key : DEFAULT_BUDDY_KEY;
}

export function buddyFaceSrc(key: string, variant: number): string {
  const art = BUDDY_ART[key] ?? BUDDY_ART[DEFAULT_BUDDY_KEY];
  const v = Math.min(Math.max(1, Math.round(variant)), BUDDY_FACE_COUNT);
  return `/buddies/faces/${art.id}-${v}.webp`;
}

export function buddyShopSrc(key: string): string {
  const art = BUDDY_ART[key] ?? BUDDY_ART[DEFAULT_BUDDY_KEY];
  return `/buddies/shop/${art.id}.webp`;
}

// Scenes under public/buddies/memories/<id>-l<n>.webp; tanuki-l2 is still owed.
const MEMORY_ART_LEVELS: Record<string, readonly number[]> = {
  tango: [2, 3, 4, 5],
  bunny: [2, 3, 4, 5],
  penguin: [2, 3, 4, 5],
  panda: [2, 3, 4, 5],
  fox: [2, 3, 4, 5],
  calico: [2, 3, 4, 5],
  otter: [2, 3, 4, 5],
  luckycat: [2, 3, 4, 5],
  kappa: [2, 3, 4, 5],
  tanuki: [3, 4, 5],
  redpanda: [2, 3, 4, 5],
};

export function buddyMemorySrc(key: string, level: number): string | null {
  const art = BUDDY_ART[key];
  if (!art || !MEMORY_ART_LEVELS[art.id]?.includes(level)) return null;
  return `/buddies/memories/${art.id}-l${level}.webp`;
}

export function randomFaceVariant(): number {
  return 1 + Math.floor(Math.random() * BUDDY_FACE_COUNT);
}

// ─── Avatars ─────────────────────────────────────────────────────────────────
// A user avatar is a buddy face, stored on profiles.avatar as
// '<shop item key>:<face variant>' (e.g. 'buddy_fox:3'). Owning a buddy in the
// shop is what unlocks its faces; buddy_tango is free, so everyone has avatars.

export interface AvatarRef {
  buddyKey: string;
  variant: number;
}

export function makeAvatar(buddyKey: string, variant: number): string {
  return `${buddyKey}:${variant}`;
}

/**
 * Null for anything that doesn't resolve to a real face — unknown buddy keys
 * (e.g. a buddy later removed from the registry) and out-of-range variants —
 * so every surface falls back to the initial instead of a broken image.
 */
export function parseAvatar(value: string | null | undefined): AvatarRef | null {
  if (!value) return null;
  const sep = value.lastIndexOf(':');
  if (sep === -1) return null;
  const buddyKey = value.slice(0, sep);
  const variant = Number(value.slice(sep + 1));
  if (!BUDDY_ART[buddyKey]) return null;
  if (!Number.isInteger(variant) || variant < 1 || variant > BUDDY_FACE_COUNT) return null;
  return { buddyKey, variant };
}

export function avatarSrc(value: string | null | undefined): string | null {
  const ref = parseAvatar(value);
  return ref ? buddyFaceSrc(ref.buddyKey, ref.variant) : null;
}

export function avatarAccent(value: string | null | undefined): string | null {
  const ref = parseAvatar(value);
  return ref ? BUDDY_ART[ref.buddyKey].accent : null;
}

export function avatarBg(value: string | null | undefined): string | null {
  const ref = parseAvatar(value);
  return ref ? BUDDY_ART[ref.buddyKey].bg : null;
}

export const FALLBACK_REACTIONS: Record<'correct' | 'wrong' | 'idle', string[]> = {
  correct: ['Yay! You got it!', 'Amazing!', 'Sugoi!', 'That was great!'],
  wrong: ['Almost! Try again!', "Don't give up!", 'One more try!'],
  idle: ["Let's study together!", '~cheers you on~', 'You can do it!'],
};
