// Base characters only. Voiced and combination characters get a hint derived
// from their base in kanaCurriculum.ts, so they are absent here on purpose.
export interface KanaMnemonic {
  en: string;
  ja: string;
}

export const HIRAGANA_MNEMONICS: Record<string, KanaMnemonic> = {
  あ: { en: 'An A with a ribbon tied across it.', ja: 'Ａに リボンを むすんだ かたち。' },
  い: { en: 'Two fish swimming side by side.', ja: 'さかなが ２ひき ならんでいる。' },
  う: { en: 'A face looking up at the sky.', ja: 'うえを 見ている よこがお。' },
  え: { en: 'A figure with a long scarf trailing behind.', ja: 'ながい マフラーの ひと。' },
  お: { en: 'Like あ, but mid-cartwheel with an extra kick.', ja: 'あ に けりを たした かたち。' },
  か: { en: 'A kite with its string.', ja: 'いとの ついた たこ。' },
  き: { en: 'A key with two teeth.', ja: 'ギザギザが ２つの かぎ。' },
  く: { en: "A bird's beak opening.", ja: 'とりの くちばし。' },
  け: { en: 'A keg with a handle on its left.', ja: 'ひだりに とってが ある たる。' },
  こ: { en: 'Two coins stacked.', ja: 'コインが ２まい。' },
  さ: { en: 'A sail on a mast, leaning.', ja: 'かたむいた ほばしら。' },
  し: { en: 'A single fishing line curving up.', ja: 'つりいとが １ぽん。' },
  す: { en: 'A loop with a tail, like a swing.', ja: 'わっかと しっぽ、ブランコ。' },
  せ: { en: 'A mouth with a straw in it.', ja: 'ストローを くわえた くち。' },
  そ: { en: 'A zigzag stitch of thread.', ja: 'ジグザグの ぬいめ。' },
  た: { en: 'A "t" and an "a" standing together.', ja: 'ｔ と ａ が ならんでいる。' },
  ち: { en: 'A cheerleader bending backwards.', ja: 'うしろに そった ひと。' },
  つ: { en: 'A tsunami wave curling over.', ja: 'まきあがる なみ。' },
  て: { en: 'A hand reaching out.', ja: 'さしだした て。' },
  と: { en: 'A toe with a splinter in it.', ja: 'とげの ささった つまさき。' },
  な: { en: 'A nail hammered into a plank.', ja: 'いたに うった くぎ。' },
  に: { en: 'A needle and thread, two knees.', ja: 'はりと いと、ひざが ２つ。' },
  ぬ: { en: 'Noodles twirled on a stick.', ja: 'はしに まいた めん。' },
  ね: { en: 'A cat with a curled tail.', ja: 'しっぽが まるい ねこ。' },
  の: { en: 'A "no entry" swirl.', ja: 'とおれない しるしの うずまき。' },
  は: { en: 'A house with a chimney.', ja: 'えんとつの ある いえ。' },
  ひ: { en: 'A wide smile.', ja: 'おおきな えがお。' },
  ふ: { en: 'Mount Fuji with two clouds.', ja: 'ふじさんと くもが ２つ。' },
  へ: { en: 'A gentle hill.', ja: 'なだらかな おか。' },
  ほ: { en: 'は with one more bar — a taller house.', ja: 'は より せの たかい いえ。' },
  ま: { en: 'A ball of yarn on a stick.', ja: 'ぼうに まいた けいと。' },
  み: { en: 'The number 21 written quickly.', ja: '２１を はやがきした かたち。' },
  む: { en: "A cow's face saying muu.", ja: 'モーと なく うしの かお。' },
  め: { en: 'An eye with a lash — ぬ without the loop.', ja: 'まつげの ある め。' },
  も: { en: 'A fishhook with two worms on it.', ja: 'えさが ２つ ついた つりばり。' },
  や: { en: 'A yacht under sail.', ja: 'ほを はった ヨット。' },
  ゆ: { en: 'A fish swimming through a loop.', ja: 'わを くぐる さかな。' },
  よ: { en: 'A yoyo on its string.', ja: 'いとの ついた ヨーヨー。' },
  ら: { en: 'A rabbit sitting up.', ja: 'すわった うさぎ。' },
  り: { en: 'Two river banks.', ja: 'かわの りょうぎし。' },
  る: { en: 'A road ending in a loop.', ja: 'わっかで おわる みち。' },
  れ: { en: 'Like る, but the loop flew away.', ja: 'る の わが とんでいった。' },
  ろ: { en: 'る with no loop — an open road.', ja: 'わの ない みち。' },
  わ: { en: 'ね with a straight tail — a swan.', ja: 'しっぽが まっすぐな ね、はくちょう。' },
  を: { en: 'Someone doing a wobbly dance kick.', ja: 'ふらふら けりを だす ひと。' },
  ん: { en: 'A quick "n" scribble.', ja: 'さっと かいた ｎ。' },
};

export const KATAKANA_MNEMONICS: Record<string, KanaMnemonic> = {
  ア: { en: 'An A with one leg kicked out.', ja: 'かたあしを だした Ａ。' },
  イ: { en: 'An arrow pointing up and left.', ja: 'ひだり うえを さす やじるし。' },
  ウ: { en: 'A roof over a small window.', ja: 'まどの うえの やね。' },
  エ: { en: 'A capital E turned on its side.', ja: 'よこに した Ｅ。' },
  オ: { en: 'A tall pole with a hook.', ja: 'かぎの ついた たかい ぼう。' },
  カ: { en: 'か without its dot.', ja: 'か から てんを とった かたち。' },
  キ: { en: 'A key sticking straight up.', ja: 'まっすぐ たった かぎ。' },
  ク: { en: 'A corner cut off.', ja: 'かどを きりおとした かたち。' },
  ケ: { en: 'A K with a bar through it.', ja: 'ぼうの とおった Ｋ。' },
  コ: { en: 'Two sides of an open box.', ja: 'はこの ２つの へん。' },
  サ: { en: 'A plus sign with a tail.', ja: 'しっぽの ある プラス。' },
  シ: { en: 'Two dashes at the LEFT, stroke sweeping up.', ja: 'てんが ひだり、したから うえへ。' },
  ス: { en: 'A slide going down.', ja: 'すべりだい。' },
  セ: { en: 'せ with its bottom cut short.', ja: 'したを みじかくした せ。' },
  ソ: {
    en: 'One dash at the TOP, stroke coming down.',
    ja: 'てんが うえに １つ、うえから した へ。',
  },
  タ: { en: 'ク with a stripe added.', ja: 'ク に せんを たした かたち。' },
  チ: { en: 'A plus sign wearing a hat.', ja: 'ぼうしを かぶった プラス。' },
  ツ: {
    en: 'Two dashes at the TOP, stroke coming down.',
    ja: 'てんが うえに ２つ、うえから した へ。',
  },
  テ: { en: 'A telephone pole with two wires.', ja: 'でんせんが ２ほんの でんちゅう。' },
  ト: { en: 'The letters t and o pressed together.', ja: 'ｔ と ｏ を かさねた かたち。' },
  ナ: { en: 'A knife crossing a stick.', ja: 'ぼうを よこぎる ナイフ。' },
  ニ: { en: 'Two lines — 二 means two.', ja: 'せんが ２ほん、「二」。' },
  ヌ: { en: 'ス with a stripe added.', ja: 'ス に せんを たした かたち。' },
  ネ: { en: 'A tree with roots showing.', ja: 'ねが みえる き。' },
  ノ: { en: 'One diagonal stroke.', ja: 'ななめの せんが １ぽん。' },
  ハ: { en: 'Two legs stepping apart.', ja: 'ひらいた ２ほんの あし。' },
  ヒ: { en: 'The heel of a boot.', ja: 'ブーツの かかと。' },
  フ: { en: 'A single hook.', ja: 'かぎが １つ。' },
  ヘ: { en: 'The same gentle hill as へ.', ja: 'へ と おなじ おか。' },
  ホ: { en: 'A tree with a crossbar.', ja: 'よこぼうの ある き。' },
  マ: { en: 'A mat folded over at the corner.', ja: 'かどを おった マット。' },
  ミ: { en: 'Three dashes — 三 means three.', ja: 'てんが ３つ、「三」。' },
  ム: { en: "A cow's horn.", ja: 'うしの つの。' },
  メ: { en: 'An X marking the spot.', ja: 'ばしょを しめす バツじるし。' },
  モ: { en: 'も straightened out.', ja: 'も を まっすぐに した かたち。' },
  ヤ: { en: 'An arrow crossed by a bar.', ja: 'ぼうの とおった やじるし。' },
  ユ: { en: 'A U turned into a shelf.', ja: 'たなに なった Ｕ。' },
  ヨ: { en: 'Three prongs of a fork.', ja: 'フォークの ３ほんの は。' },
  ラ: { en: 'A hook wearing a hat.', ja: 'ぼうしを かぶった かぎ。' },
  リ: { en: 'Two river banks, straightened.', ja: 'まっすぐな かわの りょうぎし。' },
  ル: { en: 'Two legs running.', ja: 'はしる ２ほんの あし。' },
  レ: { en: 'A single check mark.', ja: 'チェックが １つ。' },
  ロ: { en: 'A square box.', ja: 'しかくい はこ。' },
  ワ: { en: 'A wide open mouth.', ja: 'おおきく あけた くち。' },
  ヲ: { en: 'ワ with a bar over the top.', ja: 'ワ の うえに ぼうを のせた かたち。' },
  ン: {
    en: 'One dash at the TOP, stroke sweeping up.',
    ja: 'てんが うえに １つ、したから うえへ。',
  },
};
