-- Custom show cards generated by users in Point & Communicate (Travel Mode)
CREATE TABLE show_cards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category TEXT NOT NULL DEFAULT 'custom',
  english TEXT NOT NULL,
  japanese TEXT NOT NULL,
  romaji TEXT NOT NULL,
  situation TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '💬',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for loading a user's cards
CREATE INDEX idx_show_cards_user_id ON show_cards(user_id);

-- RLS
ALTER TABLE show_cards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own show cards"
  ON show_cards FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own show cards"
  ON show_cards FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own show cards"
  ON show_cards FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own show cards"
  ON show_cards FOR DELETE
  USING (auth.uid() = user_id);
